import {
  Apple,
  Archive,
  Baby,
  Bath,
  BedDouble,
  Beef,
  Briefcase,
  Building2,
  Car,
  Coffee,
  Cookie,
  CupSoda,
  Dog,
  DoorClosed,
  Droplets,
  Heart,
  House,
  Lamp,
  Leaf,
  Milk,
  Package,
  PawPrint,
  Pill,
  Refrigerator,
  Shirt,
  ShoppingBasket,
  Snowflake,
  Soup,
  Sparkles,
  SprayCan,
  Star,
  Tag,
  Tent,
  TreePalm,
  UtensilsCrossed,
  Warehouse,
  WashingMachine,
  Wheat,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

// Registro de íconos disponibles. En la base de datos se guarda solo la clave.
export const ICONS: Record<string, LucideIcon> = {
  home: House,
  'building-2': Building2,
  warehouse: Warehouse,
  tent: Tent,
  'tree-palm': TreePalm,
  briefcase: Briefcase,
  refrigerator: Refrigerator,
  snowflake: Snowflake,
  'utensils-crossed': UtensilsCrossed,
  bath: Bath,
  'bed-double': BedDouble,
  shirt: Shirt,
  package: Package,
  archive: Archive,
  sparkles: Sparkles,
  'spray-can': SprayCan,
  droplets: Droplets,
  'paw-print': PawPrint,
  dog: Dog,
  apple: Apple,
  milk: Milk,
  'cup-soda': CupSoda,
  wheat: Wheat,
  beef: Beef,
  soup: Soup,
  cookie: Cookie,
  coffee: Coffee,
  pill: Pill,
  'shopping-basket': ShoppingBasket,
  tag: Tag,
  star: Star,
  heart: Heart,
  leaf: Leaf,
  'washing-machine': WashingMachine,
  'door-closed': DoorClosed,
  lamp: Lamp,
  car: Car,
  wrench: Wrench,
  baby: Baby,
}

export const ICON_KEYS = Object.keys(ICONS)

export const INVENTORY_ICON_KEYS = [
  'home',
  'building-2',
  'warehouse',
  'tent',
  'tree-palm',
  'briefcase',
  'car',
  'heart',
  'star',
  'package',
]

export function getIcon(key: string | null | undefined): LucideIcon {
  return (key && ICONS[key]) || Package
}
